import type { Metadata } from "next";
import { Kufam } from "next/font/google"
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const kufam = Kufam({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zenya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="pt-BR">
        <body
          className={`${kufam.className} antialiased`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
