import type { Metadata } from "next";
import { Kufam } from "next/font/google"
import "./globals.css";

const kufam = Kufam({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kufam.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
